### ISSUE TITLE
这个是在官方固件开启ssh的情况下安装uu加速器插件吗

### ISSUE THREAD

**Issue by yxl0118** [kaedeair/UUplugin-install-AX6#1]

**Comment by kaedeair** [comment]
需要解锁ssh才能进入shell

**Comment by yxl0118** [comment]
ok 那么我按照您的教程可以在官方固件的情况下 给ax6装上小米的uu插件是吗

**Comment by yxl0118** [comment]
这个插件安装好后 是可以加速pc游戏的吧

**Comment by kaedeair** [comment]
官方固件用这个脚本可以安装，插件只能支持主机游戏

**Comment by yxl0118** [comment]
小米ax3600自带的uu插件可以加速电脑游戏，那么如果将uu官方给的插件替换成小米路由器的uu插件再使用您的脚本可以使得红米ax6安装上小米ax3600的uu插件并且获得小米ax3600的使用体验吗？
有一个类似案例可以麻烦参考一下吗？感谢！https://www.right.com.cn/forum/thread-8289124-1-1.html

**Comment by kaedeair** [comment]
这个脚本安装的是官方的openwrt版本加速插件，与小米特供版不同，不能混用
